//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AeroBeatTools.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AeroBeatTools.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Audio に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Audio {
            get {
                return ResourceManager.GetString("Audio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Disable PortAudio に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AudioDisablePortAudio {
            get {
                return ResourceManager.GetString("AudioDisablePortAudio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Minimize window and mute sounds に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AudioMinimizeMute {
            get {
                return ResourceManager.GetString("AudioMinimizeMute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   PortAudio Device Settings に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AudioPortAudioDeviceSettings {
            get {
                return ResourceManager.GetString("AudioPortAudioDeviceSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Use default audio device に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AudioPortAudioUseDefaultAudioDevice {
            get {
                return ResourceManager.GetString("AudioPortAudioUseDefaultAudioDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   BMS Directories に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string BMSDirectories {
            get {
                return ResourceManager.GetString("BMSDirectories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Add に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string BMSDirectoriesAdd {
            get {
                return ResourceManager.GetString("BMSDirectoriesAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Delete に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string BMSDirectoriesDelete {
            get {
                return ResourceManager.GetString("BMSDirectoriesDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Scan BMS at start に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string BMSDirectoriesScanAtStart {
            get {
                return ResourceManager.GetString("BMSDirectoriesScanAtStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Exit に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Graphics に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Graphics {
            get {
                return ResourceManager.GetString("Graphics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Framerate: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GraphicsFramerate {
            get {
                return ResourceManager.GetString("GraphicsFramerate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Wait V-Sync に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GraphicsFramerateWaitVSync {
            get {
                return ResourceManager.GetString("GraphicsFramerateWaitVSync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Fullscreen に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GraphicsFullscreen {
            get {
                return ResourceManager.GetString("GraphicsFullscreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Quality: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GraphicsQuality {
            get {
                return ResourceManager.GetString("GraphicsQuality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Use bilinear interpolation when using different resolution skin に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GraphicsQualitySceneFilter {
            get {
                return ResourceManager.GetString("GraphicsQualitySceneFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Resolution: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GraphicsResolution {
            get {
                return ResourceManager.GetString("GraphicsResolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Custom:  に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GraphicsResolutionCustom {
            get {
                return ResourceManager.GetString("GraphicsResolutionCustom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   HD (1280x720) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GraphicsResolutionHD {
            get {
                return ResourceManager.GetString("GraphicsResolutionHD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SD (640x480) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GraphicsResolutionSD {
            get {
                return ResourceManager.GetString("GraphicsResolutionSD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Start AeroBeat に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StartAeroBeat {
            get {
                return ResourceManager.GetString("StartAeroBeat", resourceCulture);
            }
        }
    }
}
